// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMvDuImhFTuMVOSnhblS9uuuBTwNyYT4w',
    appId: '1:1082500530666:web:db922087a757adfc56f293',
    messagingSenderId: '1082500530666',
    projectId: 'miral-bit',
    authDomain: 'miral-bit.firebaseapp.com',
    storageBucket: 'miral-bit.appspot.com',
    measurementId: 'G-04DPSG99L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMozkWArmiy5LcyJBdlE907MF5Sxo5R_E',
    appId: '1:1082500530666:android:62d8b43ffc030ba056f293',
    messagingSenderId: '1082500530666',
    projectId: 'miral-bit',
    storageBucket: 'miral-bit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHf9a5WS2ScuKCYNMiKfJYwgI2v6GQo5k',
    appId: '1:1082500530666:ios:6b535a0cbae514bf56f293',
    messagingSenderId: '1082500530666',
    projectId: 'miral-bit',
    storageBucket: 'miral-bit.appspot.com',
    iosBundleId: 'com.miral.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHf9a5WS2ScuKCYNMiKfJYwgI2v6GQo5k',
    appId: '1:1082500530666:ios:6b535a0cbae514bf56f293',
    messagingSenderId: '1082500530666',
    projectId: 'miral-bit',
    storageBucket: 'miral-bit.appspot.com',
    iosBundleId: 'com.miral.cryptoCoinsList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMvDuImhFTuMVOSnhblS9uuuBTwNyYT4w',
    appId: '1:1082500530666:web:41f8fdb37de24ca056f293',
    messagingSenderId: '1082500530666',
    projectId: 'miral-bit',
    authDomain: 'miral-bit.firebaseapp.com',
    storageBucket: 'miral-bit.appspot.com',
    measurementId: 'G-B45NLWL2E6',
  );
}
